version: '3'

services:
  node-graphql:
    build: 
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: node-grpc
    env_file:
      - .env
    command: npm run start
    ports:
      - 50051:50051
    volumes:
      - /usr/src/app/node_modules
      - ./:/usr/src/app